#!/usr/bin/env bash
# Launch one grid cell detached, so it outlives the shell that started it.
#
#   bash scripts/launch_cell.sh <outdir> <config> <envfile> <environment> \
#                               <agent> <launch-model> <wire-model> <wandb-run>
#
#   outdir        path under runs/, e.g. officeqa/gpt-5.6-sol-codex-r2
#   config        build.yaml, relative to the vero/ package dir
#   envfile       credential file in vero/, e.g. heb.secrets.env (gitignored)
#   environment   outer harbor environment, normally `modal`
#   agent         optimizer harness: claude-code | opencode | codex | kimi-cli
#   launch-model  the form the HARNESS wants (see CONFIGURATION.md routing table):
#                   claude-code  bare          claude-opus-5
#                   opencode     provider/     anthropic/claude-opus-5
#                   codex        bare          gpt-5.6-sol
#                   kimi-cli     doubled       openai/fireworks_ai/kimi-k3
#   wire-model    the form the GATEWAY sees, which fills the producer allow-list
#                 via --param optimizer_model. Usually the launch-model minus the
#                 harness-specific prefix: claude-opus-5, fireworks_ai/kimi-k3.
#   wandb-run     <benchmark>__<model>__<harness>__r<n>
#   [extra...]    optional trailing KEY=VALUE pairs, each forwarded as --param.
#                 Needed by configs whose producer allow-list has more than one
#                 slot: swe-atlas-qna and tau3's gpt-5.4-mini variant take
#                 optimizer_model_bare and optimizer_aux_model as well, and an
#                 anthropic-routed optimizer must pass them explicitly because the
#                 defaults resolve to the OpenAI family. The gateway compares exact
#                 strings, so a missing slot is a 403 model_denied on that model.
#
# Why the daemonizer: macOS has no setsid(1), and the harness SIGTERMs background
# tasks belonging to an idle session's process group. A plain `nohup ... &` loses
# the run. This double-forks into a new session instead.
#
# This script fails loudly on every error. Do not wrap calls to it in `|| true`
# in a loop -- a launch that silently no-ops reads exactly like a launch that
# worked, and that has already cost us a full grid once.
set -euo pipefail

if [ "$#" -lt 8 ]; then
  sed -n '2,36p' "$0" >&2
  exit 2
fi

outdir=$1 config=$2 envfile=$3 environment=$4
agent=$5 launch_model=$6 wire_model=$7 wandb_run=$8
shift 8
# Each remaining KEY=VALUE becomes its own --param. Validated here rather than
# passed through blind, so a typo fails at launch instead of at the gateway.
extra_params=""
for pair in "$@"; do
  case "$pair" in
    *=*) extra_params="$extra_params \\
  --param \"$pair\"" ;;
    *) echo "extra args must be KEY=VALUE, got: $pair" >&2; exit 2 ;;
  esac
done

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo=$(cd "$here/../.." && pwd)
pkg="$repo/vero"
rundir="$repo/runs/$outdir"

[ -f "$pkg/$envfile" ] || { echo "no credential file: vero/$envfile" >&2; exit 1; }
[ -f "$pkg/$config" ] || { echo "no config: vero/$config" >&2; exit 1; }
if [ -f "$rundir/run.pid" ] && kill -0 "$(cat "$rundir/run.pid")" 2>/dev/null; then
  echo "$outdir already has a live pid $(cat "$rundir/run.pid")" >&2
  exit 1
fi

mkdir -p "$rundir/jobs"
# Every interpolated value is quoted in the generated script. Without it a repo
# path containing a space word-splits at run time and passes wrong arguments,
# which surfaces as a mis-configured run rather than a launcher bug.
cat > "$rundir/launch.sh" <<EOF
#!/usr/bin/env bash
# Generated by launch_cell.sh -- edit that, not this.
set -euo pipefail
cd "$pkg"
exec uv run vero harbor run \\
  --config "$config" \\
  --env-file "$envfile" \\
  --environment "$environment" \\
  --agent "$agent" \\
  --model "$launch_model" \\
  --param "optimizer_model=$wire_model" \\
  --param "wandb_run=$wandb_run"$extra_params \\
  --yes \\
  -o "$rundir/jobs"
EOF

cat > "$rundir/daemonize.py" <<'EOF'
#!/usr/bin/env python3
"""Double-fork launch.sh into its own session so it outlives this shell."""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPT = os.path.join(HERE, "launch.sh")
LOG = os.path.join(HERE, "run.log")
PIDFILE = os.path.join(HERE, "run.pid")

if os.fork() != 0:
    os._exit(0)  # parent returns to the shell immediately
os.setsid()  # new session: detached from the caller's process group
if os.fork() != 0:
    os._exit(0)  # ensure we can never reacquire a controlling terminal

with open(LOG, "ab", buffering=0) as log, open(os.devnull, "rb") as null:
    os.dup2(null.fileno(), 0)
    os.dup2(log.fileno(), 1)
    os.dup2(log.fileno(), 2)
with open(PIDFILE, "w") as handle:
    handle.write(str(os.getpid()))
os.execv("/bin/bash", ["/bin/bash", SCRIPT])
sys.exit(1)
EOF

rm -f "$rundir/run.pid"
python3 "$rundir/daemonize.py"

# The daemonizer returns immediately; give the grandchild a moment to write its
# pid, then prove it is actually running. run.log is appended to, not truncated,
# so a relaunch of the same cell keeps the earlier attempt's output above.
for _ in $(seq 20); do
  [ -s "$rundir/run.pid" ] && break
  sleep 0.5
done
pid=$(cat "$rundir/run.pid" 2>/dev/null || true)
if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then
  echo "FAILED to start $outdir -- see runs/$outdir/run.log" >&2
  exit 1
fi
echo "started $outdir  pid=$pid  agent=$agent  model=$launch_model  wandb=$wandb_run"
