[project]
name = "tau_bench"
version = "0.1.0"
description = "The Tau-Bench package"
authors = [
    {name = "Sierra", email = "-"},
    {name = "-", email = "-"},
]
dependencies = [
    "setuptools>=80.9.0",
    "anthropic>=0.26.1",
    "datasets>=2.14.0",
    "google-generativeai>=0.5.4",
    "litellm>=1.41.0",
    "mistralai>=0.4.0",
    "numpy>=1.26.4",
    "openai>=1.13.3",
    "scale-vero-tasks>=0.1.0",
    "tenacity>=8.3.0",
    "termcolor>=2.4.0",
    "tqdm>=4.66.0",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.uv.sources]
scale-vero-tasks = { path = "../../../vero-tasks", editable = true }
